/* Chiang Mai v16 shared itinerary editor. Load after sheet-sync + itinerary-merge-core. */
(()=>{
'use strict';
const core=window.CMItineraryMerge;if(!core)return;
const K='cm26_itinerary_v1',SYNC_KEY='cm26_notes_sync_key',API='https://striking-determination-production-6964.up.railway.app';
const F=['date','time','type','title','zone','priority','arrangement','rain','packing','notes','mode','order'];
const L={date:'日期',time:'時間',type:'類型',title:'行程／地點',zone:'區域',priority:'優先',arrangement:'安排',rain:'雨天／取消處理',packing:'準備／攜帶',notes:'注意事項',mode:'適用計畫',order:'排序'};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const auth=()=>{try{return window.currentAuth?.()?.identity||null}catch{return null}};
const toast=s=>typeof window.toast==='function'?window.toast(s):alert(s);
const dates=()=>typeof daily==='undefined'?[]:daily.map(x=>x['日期']).filter(Boolean);
function h(s){let a=2166136261,b=3339675911;for(const ch of s){const c=ch.charCodeAt(0);a=Math.imul(a^c,16777619);b=Math.imul(b^c,2246822519)}return(a>>>0).toString(16).padStart(8,'0')+(b>>>0).toString(16).padStart(8,'0')}
function source(){const out={},seen=new Map();(typeof events==='undefined'?[]:events).forEach((r,i)=>{const date=String(r['日期']||''),title=String(r['行程/地點']||'').trim();if(!date||!title)return;const k=`${date}\u001f${title}`,n=(seen.get(k)||0)+1;seen.set(k,n);const id=`src-${h(`${k}\u001f${n}`)}`;out[id]={date,time:String(r['時間']??''),type:String(r['類型']??''),title,zone:String(r['區域']??''),priority:String(r['優先']??''),arrangement:String(r['建議安排']??''),rain:String(r['雨天/取消處理']??''),packing:String(r['準備/攜帶']??''),notes:String(r['注意事項']??''),mode:'ALL',order:String(i*10),budgetLow:String(r['2人低THB']??''),budgetHigh:String(r['2人高THB']??'')}});return out}
function blank(){return{version:1,source:{},orphans:{},overrides:{},synced:{},dirty:[],sourceConflicts:[]}}
function load(){try{const x=JSON.parse(localStorage.getItem(K)||'null');return x?.version===1?x:blank()}catch{return blank()}}
let doc=load(),src=source(),remoteConflicts=[];
const save=()=>localStorage.setItem(K,JSON.stringify(doc));
const dirty=id=>{if(!doc.dirty.includes(id))doc.dirty.push(id)};
function reconcile(){doc.orphans=doc.orphans||{};doc.sourceConflicts=doc.sourceConflicts||[];if(Object.keys(doc.source||{}).length){const m=core.mergeSource(doc.source,src,doc.overrides||{});doc.overrides=m.overrides;for(const c of m.conflicts)if(!src[c.id]&&doc.source[c.id])doc.orphans[c.id]=doc.source[c.id];doc.sourceConflicts=[...new Map([...doc.sourceConflicts,...m.conflicts].map(c=>[`${c.id}:${c.kind}:${(c.fields||[]).join(',')}`,c])).values()];for(const id of Object.keys(doc.overrides))if(!core.equal(doc.overrides[id],doc.synced[id]))dirty(id)}doc.source=src;save()}
function base(id){return src[id]||doc.orphans?.[id]||null}
function item(id){const b=base(id),o=doc.overrides?.[id];return b||o?{...b,...(o?.patch||{}),id,custom:!!o?.custom}:null}
function list(date,mode){const out=[];for(const id of new Set([...Object.keys(src),...Object.keys(doc.overrides||{})])){const o=doc.overrides?.[id];if(o?.deleted)continue;const x=item(id);if(!x)continue;if(x.date===date&&(!x.mode||x.mode==='ALL'||x.mode===mode))out.push(x)}return out.sort((a,b)=>Number(a.order||0)-Number(b.order||0)||String(a.time).localeCompare(String(b.time))||a.id.localeCompare(b.id))}
function modal(){let m=document.getElementById('cmItineraryModal');if(m)return m;m=document.createElement('div');m.id='cmItineraryModal';m.className='cm-it-modal';m.innerHTML='<form class="cm-it-panel"><div class="cm-it-head"><h2>編輯行程</h2><button type="button" data-close>×</button></div><div class="cm-it-fields"></div><div class="cm-it-actions"><button class="btn secondary" type="button" data-close>取消</button><button class="btn" type="submit">儲存</button></div></form>';document.body.appendChild(m);m.addEventListener('click',e=>{if(e.target===m||e.target.closest('[data-close]'))m.classList.remove('open')});m.querySelector('form').addEventListener('submit',saveForm);return m}
function field(k,v){if(k==='date')return`<label>${L[k]}<select data-f="date">${dates().map(d=>`<option ${d===v?'selected':''}>${esc(d)}</option>`).join('')}</select></label>`;if(k==='mode')return`<label>${L[k]}<select data-f="mode">${[['ALL','A／B／C 共用'],['A','僅 A'],['B','僅 B'],['C','僅 C']].map(([x,t])=>`<option value="${x}" ${x===v?'selected':''}>${t}</option>`).join('')}</select></label>`;if(['arrangement','rain','packing','notes'].includes(k))return`<label>${L[k]}<textarea data-f="${k}" rows="3">${esc(v)}</textarea></label>`;return`<label>${L[k]}<input data-f="${k}" value="${esc(v)}" ${k==='title'?'required':''}></label>`}
function open(id=''){if(!auth()){toast('請先登入才能編輯行程');return}const m=modal(),x=id?item(id):{date:String(window.stateGet?.('selectedDate','')||dates()[0]),mode:'ALL',time:'',type:'',title:'',zone:'',priority:'中',arrangement:'',rain:'',packing:'',notes:''};m.dataset.id=id;m.querySelector('h2').textContent=id?'編輯行程項目':'新增共同日程';m.querySelector('.cm-it-fields').innerHTML=['date','time','type','title','zone','priority','mode','arrangement','rain','packing','notes'].map(k=>field(k,String(x[k]??''))).join('');m.classList.add('open')}
function saveForm(e){e.preventDefault();const m=modal(),oldId=m.dataset.id,id=oldId||`add-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,10)}`,custom=!oldId||!!doc.overrides?.[id]?.custom,v=Object.fromEntries([...m.querySelectorAll('[data-f]')].map(el=>[el.dataset.f,el.value.trim()]));if(!dates().includes(v.date)||!v.title){toast('請填寫日期與行程名稱');return}let patch={};if(custom)patch={...v,order:item(id)?.order||String(list(v.date,v.mode).length*10+500)};else{for(const [k,val]of Object.entries(v))if(!core.equal(val,base(id)?.[k]))patch[k]=val;if(doc.overrides?.[id]?.patch?.order!==undefined)patch.order=doc.overrides[id].patch.order}doc.overrides[id]={id,custom,deleted:false,patch};dirty(id);save();m.classList.remove('open');refresh();toast('已儲存在本機，請同步共同日程')}
function del(id){const x=item(id);if(!x||!confirm(`刪除「${x.title}」？`))return;const o=doc.overrides[id]||{id,custom:!base(id),deleted:false,patch:{}};doc.overrides[id]={...o,deleted:true};dirty(id);save();refresh()}
function move(id,d){const x=item(id);if(!x)return;const a=list(x.date,String(window.stateGet?.('dayMode','A')||'A')),i=a.findIndex(y=>y.id===id),j=i+d;if(i<0||j<0||j>=a.length)return;[a[i],a[j]]=[a[j],a[i]];a.forEach((y,n)=>{doc.overrides[y.id]={id:y.id,custom:!!doc.overrides?.[y.id]?.custom,deleted:false,patch:{...(doc.overrides?.[y.id]?.patch||{}),order:String(n*10)}};dirty(y.id)});save();refresh()}
function sourceResolve(i,keep){const c=doc.sourceConflicts[i];if(!c)return;const id=c.id;if(!keep){if(c.kind==='source-removed')doc.overrides[id]={id,custom:false,deleted:true,patch:{}};else for(const k of c.fields||[])if(doc.overrides?.[id]?.patch)delete doc.overrides[id].patch[k]}else if(c.kind==='source-removed'){const p={...(doc.orphans[id]||doc.source[id]||{}),...(doc.overrides?.[id]?.patch||{})};for(const k of ['budgetLow','budgetHigh','id','custom'])delete p[k];doc.overrides[id]={id,custom:true,deleted:false,patch:p}}if(doc.overrides[id])dirty(id);doc.sourceConflicts.splice(i,1);save();refresh()}
function remoteResolve(i,keep){const c=remoteConflicts[i];if(!c)return;if(keep){doc.synced[c.id]=c.remote||null;dirty(c.id)}else{if(c.remote)doc.overrides[c.id]=c.remote;else delete doc.overrides[c.id];doc.synced[c.id]=c.remote||null;doc.dirty=doc.dirty.filter(x=>x!==c.id)}remoteConflicts.splice(i,1);save();refresh()}
async function sync(){const identity=auth();if(!identity){toast('請先登入');return}if(doc.sourceConflicts.length){toast('請先處理 XLSX 來源衝突');return}let key=localStorage.getItem(SYNC_KEY)||'';if(!key){key=(prompt('請輸入共同筆記／共同日程同步碼')||'').trim();if(!key)return;localStorage.setItem(SYNC_KEY,key)}try{const baseUrl=String(window.getPushApiBase?.()||API).replace(/\/$/,'');const changes=doc.dirty.filter(id=>doc.overrides[id]).map(id=>({id,base:doc.synced[id]||null,value:core.project(doc.overrides[id])}));const r=await fetch(`${baseUrl}/api/itinerary/sync`,{method:'POST',headers:{'Content-Type':'application/json','X-Notes-Key':key},body:JSON.stringify({identity,changes})}),data=await r.json().catch(()=>({}));if(r.status===401){localStorage.removeItem(SYNC_KEY);throw Error('同步碼不正確，已清除')}if(r.status===409){remoteConflicts=data.conflicts||[];refresh();toast('有共同修改衝突，請選擇版本');return}if(!r.ok)throw Error(data.error||`HTTP ${r.status}`);doc.synced=data.records||{};doc.overrides={...doc.synced};doc.dirty=[];remoteConflicts=[];save();refresh();toast(`共同日程同步完成（寫入 ${data.changed||0} 項）`)}catch(e){console.error(e);toast(`同步失敗，本機資料保留：${e.message}`)}}
function render(){const box=document.getElementById('dayDetail'),card=box?.querySelector('.card');if(!card)return;const date=String(window.stateGet?.('selectedDate','')||dates()[0]),mode=String(window.stateGet?.('dayMode','A')||'A');let bar=card.querySelector('#cmItToolbar');if(!bar){bar=document.createElement('div');bar.id='cmItToolbar';bar.className='cm-it-toolbar';card.querySelector('.section-head')?.insertAdjacentElement('afterend',bar)}bar.innerHTML=`<div><button class="btn soft" data-it="add">＋新增行程</button> <button class="btn secondary" data-it="sync">↻ 同步共同日程</button></div><div class="sub">${doc.dirty.length?`${doc.dirty.length} 項待同步；`:''}無衝突自動合併，衝突才詢問；XLSX 來源只隨審核後版本更新。</div>`;let st=card.querySelector('#cmItConflicts');if(!st){st=document.createElement('div');st.id='cmItConflicts';bar.after(st)}st.innerHTML='';if(doc.sourceConflicts.length)st.innerHTML+=`<div class="notice warn"><b>來源更新需確認</b>${doc.sourceConflicts.map((c,i)=>`<div>${esc(item(c.id)?.title||c.id)}：${esc(c.kind==='source-removed'?'來源已移除':'同欄位更新')} <button data-it="sm" data-i="${i}">保留我的</button> <button data-it="su" data-i="${i}">採用 XLSX</button></div>`).join('')}</div>`;if(remoteConflicts.length)st.innerHTML+=`<div class="notice warn"><b>共同同步衝突</b>${remoteConflicts.map((c,i)=>`<div>${esc(item(c.id)?.title||c.id)}：${esc((c.fields||[]).map(x=>L[x]||x).join('、'))} <button data-it="rm" data-i="${i}">保留我的</button> <button data-it="rt" data-i="${i}">採用共同版本</button></div>`).join('')}</div>`;let tl=card.querySelector('.timeline');if(!tl){tl=document.createElement('div');tl.className='timeline';card.appendChild(tl)}const rows=list(date,mode);tl.innerHTML=rows.map((x,i)=>`<div class="event"><div class="event-time">${esc(x.time)} · ${esc(x.type)}${x.custom?' · 自訂':''}</div><div class="event-title">${esc(x.title)}</div><div class="event-meta">${esc(x.zone)}　<span class="badge blue">${esc(x.priority)}</span></div><div class="event-note"><b>安排：</b>${esc(x.arrangement)}</div><div class="event-note"><b>雨天：</b>${esc(x.rain)}</div><div class="event-note"><b>準備：</b>${esc(x.packing)}</div><div class="event-note"><b>注意：</b>${esc(x.notes)}</div><div class="cm-it-buttons"><button data-it="edit" data-id="${x.id}">編輯</button><button data-it="up" data-id="${x.id}" ${i===0?'disabled':''}>↑</button><button data-it="down" data-id="${x.id}" ${i===rows.length-1?'disabled':''}>↓</button><button data-it="del" data-id="${x.id}">刪除</button></div></div>`).join('')||'<div class="notice">這個計畫暫無行程。</div>'}
function weather(){document.querySelectorAll('.weather-card > .section-head').forEach(head=>{if(head.dataset.cm16)return;const info=head.querySelector(':scope > div'),risk=head.querySelector(':scope > .weather-risk');if(!info||!risk)return;const title=info.querySelector('h4'),sub=info.querySelector('.sub');if(!title)return;head.dataset.cm16='1';title.classList.add('cm-weather-title');head.prepend(title);const row=document.createElement('div');row.className='cm-weather-row';if(sub)row.appendChild(sub);row.appendChild(risk);head.appendChild(row);if(!info.textContent.trim())info.remove()})}
function css(){const s=document.createElement('style');s.textContent=`.weather-card>.section-head{display:flex!important;flex-direction:column!important;align-items:stretch!important;gap:8px!important}.cm-weather-title{margin:0!important;font-size:clamp(12px,3.2vw,16px)!important;white-space:nowrap!important;letter-spacing:-.02em}.cm-weather-row{display:flex;justify-content:space-between;align-items:center;gap:8px;flex-wrap:wrap}.cm-it-toolbar{display:grid;gap:8px;padding:10px 0;border-bottom:1px solid var(--border);margin-bottom:10px}.cm-it-buttons{display:flex;gap:6px;flex-wrap:wrap;margin-top:9px}.cm-it-buttons button,#cmItConflicts button{border:1px solid #cbd9e8;background:#eef4fa;color:#17365d;border-radius:8px;padding:6px 9px;font-weight:700}.cm-it-modal{position:fixed;inset:0;z-index:130;background:#10182888;display:none;align-items:flex-end;justify-content:center}.cm-it-modal.open{display:flex}.cm-it-panel{background:#fff;width:min(720px,100%);max-height:91dvh;overflow:auto;border-radius:22px 22px 0 0;padding:16px}.cm-it-head{display:flex;justify-content:space-between;align-items:center}.cm-it-head button{border:0;border-radius:50%;width:38px;height:38px}.cm-it-fields{display:grid;grid-template-columns:1fr 1fr;gap:10px}.cm-it-fields label{display:grid;gap:5px;font-size:13px;font-weight:700}.cm-it-fields label:has(textarea){grid-column:1/-1}.cm-it-fields input,.cm-it-fields select,.cm-it-fields textarea{width:100%;padding:10px;border:1px solid #cbd5e1;border-radius:10px}.cm-it-actions{display:flex;justify-content:flex-end;gap:8px;margin-top:14px}@media(max-width:560px){.cm-it-fields{grid-template-columns:1fr}.cm-weather-title{font-size:clamp(11px,3vw,14px)!important}}`;document.head.appendChild(s)}
function refresh(){if(typeof window.renderDayCard==='function')window.renderDayCard(String(window.stateGet?.('selectedDate','')||dates()[0]),'dayDetail',true);weather()}
function click(e){const b=e.target.closest('[data-it]');if(!b||!document.getElementById('dayDetail')?.contains(b))return;e.preventDefault();const a=b.dataset.it,id=b.dataset.id;if(a==='add')open();else if(a==='edit')open(id);else if(a==='del')del(id);else if(a==='up')move(id,-1);else if(a==='down')move(id,1);else if(a==='sync')sync();else if(a==='sm'||a==='su')sourceResolve(Number(b.dataset.i),a==='sm');else if(a==='rm'||a==='rt')remoteResolve(Number(b.dataset.i),a==='rm')}
function init(){css();src=source();reconcile();modal();const rd=window.renderDayCard;if(typeof rd==='function'&&!rd.__cm16){const w=function(...a){const r=rd.apply(this,a);if(a[1]==='dayDetail'&&a[2])render();return r};w.__cm16=true;window.renderDayCard=w}const rw=window.renderWeatherEverywhere;if(typeof rw==='function'&&!rw.__cm16){const w=function(...a){const r=rw.apply(this,a);weather();return r};w.__cm16=true;window.renderWeatherEverywhere=w}document.addEventListener('click',click);refresh()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
